mlflow:
  experiment_name: wine
  run_name: scale
dataset:
  random_state: 57
  shuffle: True
  train_size: 0.75
  should_scale: True
train:
  structure: s
  epochs: 25
  learning_rate: 0.01
  backend: qasm_simulator
  shots: 8000
  should_normalize: True
  should_save_each_epoch: False
  on_ibmq: False